// Code generated by inuit DO NOT EDIT.

package scenes

import (
	"github.com/hajimehoshi/ebiten/v2"
	"github.com/miniscruff/igloo"
	"github.com/miniscruff/igloo/content"
	"golang.org/x/image/font/opentype"
)

type EditorAssets struct {
	NormalBackground  *ebiten.Image
	OverBackground    *ebiten.Image
	ClickedBackground *ebiten.Image
	SonoRegular       *opentype.Font
}

func (a *EditorAssets) Dispose() {
	a.NormalBackground.Dispose()
	a.OverBackground.Dispose()
	a.ClickedBackground.Dispose()
	a.SonoRegular = nil
}

func NewEditorAssets(assetLoader *igloo.AssetLoader) (*EditorAssets, error) {
	NormalBackground, err := assetLoader.LoadImage("normal_background.png")
	if err != nil {
		return nil, err
	}

	OverBackground, err := assetLoader.LoadImage("over_background.png")
	if err != nil {
		return nil, err
	}

	ClickedBackground, err := assetLoader.LoadImage("clicked_background.png")
	if err != nil {
		return nil, err
	}

	SonoRegular, err := assetLoader.LoadOpenType("Sono-Regular.ttf")
	if err != nil {
		return nil, err
	}

	return &EditorAssets{
		NormalBackground:  NormalBackground,
		OverBackground:    OverBackground,
		ClickedBackground: ClickedBackground,
		SonoRegular:       SonoRegular,
	}, nil
}

type EditorContent struct {
	NormalBackground  *content.Sprite
	OverBackground    *content.Sprite
	ClickedBackground *content.Sprite
	SonoRegular18     *content.Font
	SonoRegular24     *content.Font
	SonoRegular36     *content.Font
}

func (c *EditorContent) Dispose() {
	c.SonoRegular18.Close()
	c.SonoRegular24.Close()
	c.SonoRegular36.Close()
}

func NewEditorContent(assets *EditorAssets) (*EditorContent, error) {
	NormalBackground := &content.Sprite{
		Image: assets.NormalBackground,
	}

	OverBackground := &content.Sprite{
		Image: assets.OverBackground,
	}

	ClickedBackground := &content.Sprite{
		Image: assets.ClickedBackground,
	}

	SonoRegular18Font, err := opentype.NewFace(assets.SonoRegular, &opentype.FaceOptions{
		Size: 18,
		DPI:  72,
	})
	if err != nil {
		return nil, err
	}

	SonoRegular18 := &content.Font{
		Face: SonoRegular18Font,
	}

	SonoRegular24Font, err := opentype.NewFace(assets.SonoRegular, &opentype.FaceOptions{
		Size: 24,
		DPI:  72,
	})
	if err != nil {
		return nil, err
	}

	SonoRegular24 := &content.Font{
		Face: SonoRegular24Font,
	}

	SonoRegular36Font, err := opentype.NewFace(assets.SonoRegular, &opentype.FaceOptions{
		Size: 36,
		DPI:  72,
	})
	if err != nil {
		return nil, err
	}

	SonoRegular36 := &content.Font{
		Face: SonoRegular36Font,
	}

	return &EditorContent{
		NormalBackground:  NormalBackground,
		OverBackground:    OverBackground,
		ClickedBackground: ClickedBackground,
		SonoRegular18:     SonoRegular18,
		SonoRegular24:     SonoRegular24,
		SonoRegular36:     SonoRegular36,
	}, nil
}
